Fix terraform fmt and validate for 0.12
Without this patch make check_terraform fails, causing the lint test
pipeline to fail.  This patch updates the task to work with Terraform
0.12.

In 0.12 terraform validate requires terraform init to have run.  This
behavior is implemented in the helper script, helpers/terraform_validate

Example output:

    make check_terraform
    Running terraform fmt
    terraform fmt -diff -check=true -write=false .
    terraform fmt -diff -check=true -write=false ./examples/app_engine
    examples/app_engine/main.tf
    --- old/examples/app_engine/main.tf
    +++ new/examples/app_engine/main.tf
    @@ -22,15 +22,15 @@
       Provider configuration
      *****************************************/
     provider "gsuite" {
    -  credentials             = file(local.credentials_file_path)
    -  version                 = "~> 0.1.9"
    +  credentials = file(local.credentials_file_path)
    +  version     = "~> 0.1.9"
     }

     module "app-engine" {
    -  source            = "../../modules/app_engine"
    -  location_id    = var.location_id
    -  auth_domain    = var.auth_domain
    -  serving_status = var.serving_status
    +  source           = "../../modules/app_engine"
    +  location_id      = var.location_id
    +  auth_domain      = var.auth_domain
    +  serving_status   = var.serving_status
       feature_settings = [{ enabled = true }]
    -  project_id = "example-project"
    +  project_id       = "example-project"
     }
    terraform fmt -diff -check=true -write=false ./examples/gke_shared_vpc
    Warning: compat_xargs -t -n1 terraform fmt -diff -check=true -write=false failed with exit code 1
    Error: terraform fmt failed with exit code 1
    Check the output for diffs and correct using terraform fmt <dir>
    make: *** [check_terraform] Error 1

This patch also uses a temporary version of the network module to
correct the error:

    Error: Unsupported block type

      on .terraform/modules/vpc/terraform-google-modules-terraform-google-network-d1b6646/main.tf line 94, in resource "null_resource" "delete_default_internet_gateway_routes":
      94:   triggers {

    Blocks of type "triggers" are not expected here. Did you mean to define
    argument "triggers"? If so, use the equals sign to assign it a value.