Use kitchen-terraform 2.2.0
Without this patch CI fails with Terraform 0.12 syntax errors becasue
Terraform 0.11 is used.

    Error: Error parsing
    /tmp/build/f541ec31/terraform-google-project-factory/test/fixtures/shared_vpc_no_subnets/main.tf:
    At 26:29: Unknown token: 26:29 IDENT file

This patch upgrades to Terraform 0.12.3 using the kitchen-terraform
2.2.0 docker image.

See https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/216